-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 15:01:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokedex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokedex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokedex` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pokedex
-- -----------------------------------------------------
USE `pokedex` ;

-- -----------------------------------------------------
-- Table `pokedex`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokedex`.`user` ;

CREATE TABLE IF NOT EXISTS `pokedex`.`user` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `level` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokedex`.`pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokedex`.`pokemon` ;

CREATE TABLE IF NOT EXISTS `pokedex`.`pokemon` (
  `id` INT NOT NULL ,
  `name` VARCHAR(100) NOT NULL,
  `img` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokedex`.`package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokedex`.`package` ;

CREATE TABLE IF NOT EXISTS `pokedex`.`package` (
  `id` INT NOT NULL auto_increment,
  `user_id` INT NOT NULL,
  `pokemon_id` INT NOT NULL,
  `cp` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `up_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `up_pokemon_id_idx` (`pokemon_id` ASC) VISIBLE,
  CONSTRAINT `up_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pokedex`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `up_pokemon_id`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `pokedex`.`pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokedex`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokedex`.`type` ;

CREATE TABLE IF NOT EXISTS `pokedex`.`type` (
  `id` INT NOT NULL ,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE(`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pokemon_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokedex`.`pokemon_type` ;

CREATE TABLE IF NOT EXISTS `pokedex`.`pokemon_type` (
  `pokemon_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`pokemon_id`, `type_id`),
  INDEX `pt_type_id_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `pt_pokemon_id`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `pokedex`.`pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pt_type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `pokedex`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
